#+TITLE: Assignment
#+SUBTITLE: Data Types

* Instructions for Submission:
1. Date of Submission: *19th Jan 2022 before 11.59 PM*
2. Every program must in different file
3. Before submission rename the file as /firstname_lastname_1.py/
4. At the end you will have 5 files, make a *.zip* and submit on the link
5. The submission link is provided on *Python and Data Science* Notion Page shared with all of the students

* Assignment 1: Letter Count Application
** Description:
You are responsible for writing a program that will get a message and a specific letter from a user and then count the number of occurrences of that letter in the given message. You program should count “H” and “h” as an occurence of h. Your program will then display a message to the user stating the occurrences of the given letter.

*** Step By Step Guide:
+ Print a welcome message
+ Get user input for their name.
  + Take proper precautions to always display the name capitalized.
+ Print a message saying hello to the user using the user’s name.
+ Print a message stating the goal of the program.
+ Get user input for the message they would like to use.
+ Get user input for the letter they would like to count.
  + Standardize both the message and letter such that “H” and “h” both count as an occurrence of the letter h.
+ Create a variable called ~letter_count~ and set it equal to the number of occurrences of the given letter in the given message.
  + Use the .count() method.
+ Print a message stating the number of occurrences of the given letter in the given message.
+ Use at least 2 comments to describe sections of your code.
+ “Chunk” your code so that is readable.
+ Use appropriate and informative variable names.
+ Format your output as below.

*** Example Output:

#+begin_example
Welcome to the Letter Counter App What is your name: ram

Hello Ram!
I will count the number of times that a specific letter occurs in a message.

Please enter a message: Hello, how are you doing today? I hope that you have a happy holiday!

Which letter would you like to count the occurrences of: h
Ram, your message has 7 h's in it.
#+end_example

\pagebreak

* Assignment 2: Miles Per Hour Conversion Application
** Description:
You are responsible for writing a program that will convert any given speed in miles per hour to a more metric friendly unit of meters per second. All calculations should be rounded to a set decimal precision of 2 decimal places.

*** Step By Step Guide:
+ Print a welcome message.
+ Get user input for their speed in miles per hour.
  + Allow for a decimal speed.
+ Convert the speed in miles per hour to meters per second.
  + Use a conversion ratio of 1 mph = 0.4474 mps.
  + Use the round() function to round this speed to 2 decimal places.
  + Check the python documentation for information on how to use the round() function.
+ Print a message to the user that informs them of their speed in meters per second.
+ Use at least 2 comments to describe sections of your code.
+ “Chunk” your code so that is readable.
+ Use appropriate and informative variable names.
+ Format your output as below.

*** Example Output:
#+begin_example
Welcome to the Miles Per Hour Conversion App

What is your speed in miles per hour: 55.8
Your speed in meters per second is 24.96.
#+end_example

\pagebreak

* Assignment 3: Temperature Conversion Application
** Description:
You are responsible for writing a program that will convert a given temperature in degrees Fahrenheit to degrees Celsius and degrees Kelvin. Your program will round all conversions to a precision of four decimal places. Lastly, your program will display the results in a convenient table style format.

*** Step By Step Guide:
+ Print a welcome message.
+ Get user input for their given temperature in degrees Fahrenheit.
  + Allow for a decimal temperature.
+ Convert the temperature into both Celsius and Kelvin.
  + If you are unsure of the conversion ratios, google is your friend.
  + Round all values to 4 decimal places.
+ Display all three temperatures such that the temperature values are aligned when printing.
+ Use at least 2 comments to describe sections of your code.
+ “Chunk” your code so that is readable.
+ Use appropriate and informative variable names.
+ Format your output as below.

*** Example Output:
#+begin_example
Welcome to the Temperature Conversion App

What is the given temperature in degrees Fahrenheit: 212.52

Degrees Fahrenheit: 212.52
Degrees Celsius:    100.2889
Degrees Kelvin:     373.4389
#+end_example

\pagebreak

* Assignment 4: Right Triangle Solver Application
** Description:
You are responsible for writing a program that will calculate the hypotenuse and area of a right triangle given its two bases. Your program will round all calculations to a precision of three decimal places and provide a summary of the mathematical results.

*** Step By Step Guide:
+ Print a welcome message.
+ Get user input for the first leg of the right triangle.
+ Get user input for the second leg of the right triangle.
+ Calculate the hypotenuse of the right triangle using the Pythagorean theorem.
  + We can't actually take a square root with basic Python. In order to take a square root, we will need to import a library of extra code.
  + Type import math as the first line of code in your program.
  + This allows us to access higher level mathematical functions such as the square root function sqrt().
  + Google how to take a square root using the math library.
+ Calculate the area of the right triangle.
+ Round each value to 3 decimal places.
+ Print a message to the user informing them of both the hypotenuse and area of the given triangle.
+ Use at least 2 comments to describe sections of your code.
+ “Chunk” your code so that is readable.
+ Use appropriate and informative variable names.
+ Format your output as below.

*** Example Output:
#+begin_example
Welcome to the Right Triangle Solver App

What is the first leg of the triangle: 20
What is the second leg of the triangle: 40.5

For a triangle with legs of 20 and 40.5 the hypotenuse is 45.169.
For a triangle with legs of 20 and 40.5 the area is 405.0.
#+end_example

\pagebreak

* Assignment 5: Multiplication/Exponent Table Application
** Description:
You are responsible for writing a program that displays a multiplication table and exponentiation table for any given number. Each table should show mathematical results for operations performed with the given number and integers from 1 to 9. The program will then print a series of messages to the user describing how cool mathematics truly is.

*** Step By Step Guide:
+ Print a welcome message.
+ Get user input for their name.
+ Get user input for their number.
+ Define a variable called message that will hold the following string:
+ name.title() + ", Math is cool!"
+ Create a multiplication table that calculates the product of the number entered and the numbers 1 through 9.
+ Create an exponent table that calculates the exponential power of the number entered raised to the power 1 through 9.
+ Each result should be rounded to 4 decimal
+ Each line in your table can be created in a single print statement.
  + I would recommend getting one line to work correctly.
  + Copy and paste the line the correct number of times, changing values accordingly for each subsequent line.
  + We will later learn a more efficient way to accomplish this task.
+ Each table should have it's own heading as below
+ Each Mathematical result should be formatted as below
+ Lastly, print a series of statements using the various string methods introduced.
  + Print msg
  + Print msg in lower case
  + Print msg in title case
  + Print msg in upper case
+ Use at least 2 comments to describe sections of your code.
+ “Chunk” your code so that is readable.
+ Use appropriate and informative variable names.
+ Format your output as below.

*** Example Output:
#+begin_example
Welcome to the Multiplication/Exponent Table App
What is your name: ram
What number would you like to work with: 2.35

Multiplication Table For 2.35
    1.0 * 2.35 = 2.35
    2.0 * 2.35 = 4.7
    3.0 * 2.35 = 7.05
    4.0 * 2.35 = 9.4
    5.0 * 2.35 = 11.75
    6.0 * 2.35 = 14.1
    7.0 * 2.35 = 16.45
    8.0 * 2.35 = 18.8
    9.0 * 2.35 = 21.15

Exponent Table For 2.35
    2.35 ** 1 = 2.35
    2.35 ** 2 = 5.5225
    2.35 ** 3 = 12.9779
    2.35 ** 4 = 30.498
    2.35 ** 5 = 71.6703
    2.35 ** 6 = 168.4252
    2.35 ** 7 = 395.7993
    2.35 ** 8 = 930.1284
    2.35 ** 9 = 2185.8017

Ram Math is cool!
ram math is cool!
Ram Math Is Cool!
RAM MATH IS COOL!
#+end_example
