# NOTE: A4 paper size is 297x210, this is to help getting X and Y Coordinate when needed
import sqlite3
from fpdf import FPDF
from datetime import date
import os

# 1. Create FPDF Object
# 2. Layout ('P','L')
# 3. Unit of Measurement ('mm','cm','in')
# 4. Format ('A3', 'A4' (default), 'A5', 'Letter', 'Legal', (100,150) (custom format)
pdf = FPDF('P', 'mm', 'A4')
pdf.set_margins(left=10, top=2, right=10)
pdf.set_auto_page_break(False)

# Add Page
pdf.add_page()

register_number = ''
# Variables
collegeName1 = 'AABBCC AABBCC Shikshan Sanstha, PLACE'
collegeName2 = 'AABBCC AABBCC Institute of Technology and Research'
city = 'PLACE.'
formally = '(Formally XXXXXX College of Engineering)'
address = 'Address Address Address (STATE)'
title = 'LEAVING CERTIFICATE'
line1 = 'Approved by AICTE New Delhi, DTE Mumbai & Affiliated to Sant Gadge Baba Amravati University, Amravati'
line2 = 'No Change in this certificate shall be made except by the authority issuing it and any infringement of this' \
        'requirement liable to involve the imposition of penalty as that of restication of the pupil'
nationality = 'indian'
nationality = nationality.upper()
currentDate = date.today()


def r_no(r_numb):
    global register_number
    register_number = r_numb
    return 0


def create_pdf():
    con = sqlite3.connect('studb')
    c = con.cursor()
    c.execute("SELECT enrolment_no FROM STU_DB WHERE register_no=?", [register_number])
    enrollment_number = c.fetchone()
    c.execute("SELECT name FROM STU_DB WHERE register_no=?", [register_number])
    p_name = c.fetchone()
    c.execute("SELECT mname FROM STU_DB WHERE register_no=?", [register_number])
    p_m_name = c.fetchone()
    c.execute("SELECT lname FROM STU_DB WHERE register_no=?", [register_number])
    p_l_name = c.fetchone()
    c.execute("SELECT mother_name FROM STU_DB WHERE register_no=?", [register_number])
    mother_name = c.fetchone()
    c.execute("SELECT caste FROM STU_DB WHERE register_no=?", [register_number])
    p_caste = c.fetchone()
    c.execute("SELECT place_of_birth FROM STU_DB WHERE register_no=?", [register_number])
    p_place_of_birth = c.fetchone()
    c.execute("SELECT dob FROM STU_DB WHERE register_no=?", [register_number])
    p_dob = c.fetchone()
    c.execute("SELECT date_w FROM STU_DB WHERE register_no=?", [register_number])
    p_date_words = c.fetchone()
    c.execute("SELECT month FROM STU_DB WHERE register_no=?", [register_number])
    p_month_words = c.fetchone()
    c.execute("SELECT year FROM STU_DB WHERE register_no=?", [register_number])
    p_year_words = c.fetchone()
    c.execute("SELECT last_institute FROM STU_DB WHERE register_no=?", [register_number])
    p_last_institute = c.fetchone()
    c.execute("SELECT date_of_admission FROM STU_DB WHERE register_no=?", [register_number])
    p_date_of_admission = c.fetchone()
    c.execute("SELECT course_name FROM STU_DB WHERE register_no=?", [register_number])
    p_course_name = c.fetchone()
    c.execute("SELECT tc_no FROM STU_TC WHERE register_no=?", [register_number])
    p_tc_no = c.fetchone()
    c.execute("SELECT progress FROM STU_TC WHERE register_no=?", [register_number])
    p_progress = c.fetchone()
    c.execute("SELECT conduct FROM STU_TC WHERE register_no=?", [register_number])
    p_conduct = c.fetchone()
    c.execute("SELECT dol FROM STU_TC WHERE register_no=?", [register_number])
    p_dol = c.fetchone()
    c.execute("SELECT reason FROM STU_TC WHERE register_no=?", [register_number])
    p_reason = c.fetchone()
    c.execute("SELECT remark FROM STU_TC WHERE register_no=?", [register_number])
    p_remark = c.fetchone()
    con.commit()
    c.close()
    # Specify font
    # fonts('times', 'courier', 'helvetica', 'symbol')
    # 'B' (bold), 'U' (underline), 'I' (italics), '' (regular), combination (i.e. ('BU'))
    # pdf.set_font('helvetica', '', 16)
    pdf.set_line_width(0.5)
    pdf.image('logo.jpg', 10, 16, 28)
    pdf.set_font('times', 'B', 16)
    pdf.text(175, 30, f'{p_tc_no[0]}')
    # Add text
    # 1. w = width
    # 2. h = height
    pdf.set_font('arial', '', 12)
    pdf.cell(0, 6, collegeName1, align='C', ln=True)
    pdf.set_font('helvetica', 'B', 18)
    pdf.cell(0, 6, collegeName2, align='C', ln=True)
    pdf.cell(0, 6, city, align='C', ln=True)
    pdf.set_font('arial', '', 12)
    pdf.cell(0, 6, formally, align='C', ln=True)
    pdf.cell(0, 6, address, align='C', ln=True)
    pdf.set_font('times', 'B', 24)
    pdf.cell(0, 10, title, align='C', ln=True)
    pdf.line(0, 44, 210, 44)
    pdf.set_font('times', '', 13)
    pdf.cell(0, 10, line1, align='C', ln=True)
    pdf.line(0, 51, 210, 51)
    pdf.set_font('times', '', 13)
    pdf.multi_cell(0, 6, line2, align='C', border=0)
    pdf.line(0, 65, 210, 65)
    pdf.cell(0, 4, '', ln=True)
    pdf.set_font('times', '', 12)
    pdf.cell(70, 8, f'1. Register No.')
    pdf.set_font('times', 'B', 12)
    pdf.cell(0, 8, f': {register_number}', ln=True)
    pdf.set_font('times', '', 12)
    pdf.cell(70, 8, f'2. Enrollment No.')
    pdf.set_font('times', 'B', 12)
    pdf.cell(0, 8, f': {enrollment_number[0]}', ln=True)
    pdf.set_font('times', '', 12)
    pdf.cell(70, 8, f'3. Name of the Student')
    pdf.set_font('times', 'B', 12)
    pdf.cell(0, 8, f': {p_name[0]} {p_m_name[0]} {p_l_name[0]}', ln=True)
    pdf.set_font('times', '', 12)
    pdf.cell(70, 8, f'4. Mother\'s Name')
    pdf.set_font('times', 'B', 12)
    pdf.cell(0, 8, f': {mother_name[0]}', ln=True)
    pdf.set_font('times', '', 12)
    pdf.cell(70, 8, f'5. Caste')
    pdf.set_font('times', 'B', 12)
    pdf.cell(0, 8, f': {p_caste[0]}', ln=True)
    pdf.set_font('times', '', 12)
    pdf.cell(70, 8, '5. Nationality')
    pdf.set_font('times', 'B', 12)
    pdf.cell(0, 8, f': {nationality}', ln=True)
    pdf.set_font('times', '', 12)
    pdf.cell(70, 8, f'6. Place of Birth')
    pdf.set_font('times', 'B', 12)
    pdf.cell(0, 8, f': {p_place_of_birth[0]}', ln=True)
    pdf.set_font('times', '', 12)
    pdf.cell(70, 8, '7. Date of Birth')
    pdf.set_font('times', 'B', 12)
    pdf.cell(0, 8, f': {p_dob[0]}', ln=True)
    pdf.set_font('times', '', 10)
    pdf.cell(0, 5, '    (according to the Christian era.)', ln=True)
    pdf.set_font('times', '', 12)
    pdf.cell(70, 8, f'8. Date of Birth (In Words)')
    pdf.set_font('times', 'B', 12)
    pdf.cell(0, 8, f': {p_date_words[0]} {p_month_words[0]} {p_year_words[0]}', ln=True)
    pdf.set_font('times', '', 12)
    pdf.cell(70, 8, f'9. Institute Last Attended')
    pdf.set_font('times', 'B', 12)
    pdf.cell(2.5, 8, f':')
    pdf.multi_cell(0, 8, f'{p_last_institute[0]}', ln=True)
    pdf.set_font('times', '', 12)
    pdf.cell(70, 8, f'10. Date of Admission')
    pdf.set_font('times', 'B', 12)
    pdf.cell(0, 8, f': {p_date_of_admission[0]}', ln=True)
    pdf.set_font('times', '', 12)
    pdf.cell(70, 8, f'11. Progress')
    pdf.set_font('times', 'B', 12)
    pdf.cell(0, 8, f': {p_progress[0]}', ln=True)
    pdf.set_font('times', '', 12)
    pdf.cell(70, 8, f'12. Conduct')
    pdf.set_font('times', 'B', 12)
    pdf.cell(0, 8, f': {p_conduct[0]}', ln=True)
    pdf.set_font('times', '', 12)
    pdf.cell(70, 8, f'13. Date of Leaving Institute')
    pdf.set_font('times', 'B', 12)
    pdf.cell(0, 8, f': {p_dol[0]}', ln=True)
    pdf.set_font('times', '', 12)
    pdf.cell(70, 8, f'14. Name of the Course')
    pdf.set_font('times', 'B', 12)
    pdf.cell(0, 8, f': {p_course_name[0]}', ln=True)
    pdf.set_font('times', '', 12)
    pdf.cell(70, 8, f'15. Medium of Instruction')
    pdf.set_font('times', 'B', 12)
    pdf.cell(0, 8, f': ENGLISH', ln=True)
    pdf.set_font('times', '', 12)
    pdf.cell(70, 8, f'16. Duration of Course')
    pdf.set_font('times', 'B', 12)
    pdf.cell(70, 8, f': 04 Years', ln=True)
    pdf.set_font('times', '', 12)
    pdf.cell(70, 8, f'17. Reason for Leaving the Institution')
    pdf.set_font('times', 'B', 12)
    pdf.cell(0, 8, f': {p_reason[0]}', ln=True)
    pdf.set_font('times', '', 12)
    pdf.cell(70, 8, f'18. Remark')
    pdf.set_font('times', 'B', 12)
    pdf.cell(2.5, 8, f':')
    pdf.multi_cell(0, 8, f'{p_remark[0]}', ln=True)
    pdf.set_font('times', 'BI', 12)
    pdf.cell(0, 12, f'Certified that the above information is in accordance with the Institute Register.', align='C',
             ln=True)
    pdf.cell(0, 15, ln=True)
    pdf.set_font('times', 'B', 12)
    pdf.cell(35, 8, f'Date: {currentDate}')
    pdf.cell(70, 8)
    pdf.cell(0, 6, f'Principal', align='C', ln=True)
    pdf.cell(35, 8, f'Place: Amravati')
    pdf.cell(70, 8)
    pdf.set_font('times', '', 12)
    pdf.cell(0, 5, f'AABBCC AABBCC Institute of', align='C', ln=True)
    pdf.cell(105, 8)
    pdf.cell(0, 5, f'Technology & Research', align='C', ln=True)
    pdf.cell(105, 8)
    pdf.cell(0, 5, f'Amravati', align='C', ln=True)
    # Save the output pdf
    pdf.output('myPDF.pdf')
    # import os
    os.startfile('myPDF.pdf')
